name: Docker
on:
  schedule:
    - cron: "15 14 * * *"
  push:
    paths:
      - "Dockerfile"
      - "src/**"
      - "Cargo.lock"
      - "Cargo.toml"
      - ".dockerignore"
      - ".github/workflows/docker.yml"
    branches: [ "main", "stable" ]
    # Publish semver tags as releases.
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  docker:
    uses: JensYvanDeCraecker/chisel-operator-actions/.github/workflows/docker.yml@main
    with:
      publish: ${{ github.event_name != 'pull_request' }}
      platform: self-hosted
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
